version: '2'

services:
  sshd:
    image: xezpeleta/sshd
    #volumes:
    #  - /var/www:/var/www
    volumes:
      - ./pubkeys:/pubkeys
    environment:
      #- AUTHORIZED_KEYS=ssh-rsa AAAfsdfsafq!5554343... thisismysshpubkey 
      - AUTHORIZED_KEYS=/pubkeys
      - MOTD=Welcome! You can modify your at /var/www directory. More info, sysadmin@mydomain.com
    ports:
      - "2222:22"
