version: '2'

services:
  sshd:
    image: xezpeleta/sshd
    volumes:
      - ./pubkeys:/pubkeys
      #- /var/www:/var/www
      #- ./lshell.conf:/etc/lshell.conf
    environment:
      - SSH_USER=xabi
      # SSH_PASSWORD=changeme
      #- SSH_HOME=/var/www
      #- SSH_SHELL=/usr/bin/lshell
      - AUTHORIZED_KEYS=/pubkeys
      #- MOTD=Welcome! You can modify your files at /var/www directory. More info, sysadmin@mydomain.com
    ports:
      - "2222:22"
